#!/usr/bin/env bash

set -e

cat <<- EOF
MYSQL_ROOT_PASSWORD=${MARIADB_DEV_ROOT_PASSWORD:?}
MYSQL_USER=${MARIADB_DEV_USER:?}
MYSQL_PASSWORD=${MARIADB_DEV_PASSWORD:?}
MYSQL_DATABASE=${MARIADB_DEV_DATABASE:?}
MARIADB_ROOT_PASSWORD=${MARIADB_DEV_ROOT_PASSWORD:?}
MARIADB_USER=${MARIADB_DEV_USER:?}
MARIADB_PASSWORD=${MARIADB_DEV_PASSWORD:?}
MARIADB_DATABASE=${MARIADB_DEV_DATABASE:?}
MARIADB_AUTO_UPGRADE=yes
MARIADB_DISABLE_UPGRADE_BACKUP=yes
EOF
