#!/usr/bin/env bash

set -e

cat <<- EOF
MYSQL_ROOT_PASSWORD=${MARIADB_TEST_ROOT_PASSWORD:?}
MYSQL_USER=${MARIADB_TEST_USER:?}
MYSQL_PASSWORD=${MARIADB_TEST_PASSWORD:?}
MYSQL_DATABASE=${MARIADB_TEST_DATABASE:?}
MARIADB_ROOT_PASSWORD=${MARIADB_TEST_ROOT_PASSWORD:?}
MARIADB_USER=${MARIADB_TEST_USER:?}
MARIADB_PASSWORD=${MARIADB_TEST_PASSWORD:?}
MARIADB_DATABASE=${MARIADB_TEST_DATABASE:?}
MARIADB_AUTO_UPGRADE=yes
MARIADB_DISABLE_UPGRADE_BACKUP=yes
EOF
