#!/usr/bin/env bash

set -e

cat <<- EOF
APPLICATION_TRUST_PROXY_HEADERS=yes
APPLICATION_LOG_STDOUT=yes
APPLICATION_DATABASE_DSN=mysql://${MARIADB_DEV_USER:?}:${MARIADB_DEV_PASSWORD:?}@mariadb-dev:3306/${MARIADB_DEV_DATABASE:?}
OAUTH_PRIVATE_KEY_FILE=/project/var/oauth2.key
OAUTH_PUBLIC_KEY_FILE=/project/var/oauth2.pub
OAUTH_ENCRYPTION_KEY_FILE=/project/var/oauth2.enc
MAIL_TEMPLATE_DIR=${MAIL_TEMPLATE_DIR:-}
MAILER_DSN=${MAILER_DSN:-null://null}
MAILER_FROM_EMAIL=${MAILER_FROM_EMAIL:-no-reply@gmail.com}
MAILER_FROM_NAME=${MAILER_FROM_NAME:-DESIGN DAAS}
EOF
